app:
  environment: ${ENVIRONMENT}

database:
  host: ${HOST}
  port: ${PORT}
  user: ${USER}
  password: ${PASSWORD}
  db-name: ${DB_NAME}
  ssl-mode: "disable"

rest:
  port: 8081
  host: localhost
  endpoint-port: 82

metrics:
  port: 9100
  handle: "/metrics"

jaeger:
  name: "bbone"
  host: "jaeger"
  port: 6831